print("[[[******string methods******]]]")
print("\n")
school_name="achyuta academy matric hr sec school"
print("school name:",school_name)
print("slicing:",school_name[8:15])
print("captilize:", school_name.capitalize())
print("casefold:", school_name.casefold())
print("center:", school_name.center(80, '-'))
print("count:", school_name.count('e'))
print("endswitch:", school_name.endswith('l')) #checks 
print("find:", school_name.find("sec"))
print("index:", school_name.index("matric"))
print("is alnum:", school_name.isalnum())
print("is alpha:", school_name.isalpha())#space->false
print("is digit:", school_name.isdigit())
print("lower:", school_name.islower())
print("is upper:", school_name.isupper())
print("is space:", school_name.isspace())
print("title:", school_name.istitle())
print("joining:", '-'.join(['achyuta', 'academy']))  
print("ljust:", school_name.ljust(30, '*'))
print("lower():", school_name.lower())
print("lstrip():", school_name.lstrip())
print("partition()", school_name.partition(school_name))
print("replace():", school_name.replace('hr sec', 'primary'))
print("rfind('o'):", school_name.rfind('m'))
print("rindex('o'):", school_name.rindex('m'))
print("rjust():", school_name.rjust(50, '-'))
print("rstrip():", school_name.rstrip())
print("split():", school_name.split())
print("splitlines():", school_name.splitlines())
print("startswith():", school_name.startswith('mvm'))
print("strip():", school_name.strip(" "))
print("swapcase():", school_name.swapcase())# swap uppercase and lowercase 
print("title():", school_name.title())
print("translate:", school_name.translate(str.maketrans('a', 'A')))
print("upper:", school_name.upper())
print("zfill", "2025".zfill(5))